// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIz7s6s7XT9EC6-wHej6tIbtW1aViSYzg',
    appId: '1:493628718680:web:43a4906972c74fd46c142d',
    messagingSenderId: '493628718680',
    projectId: 'gotogether-5429a',
    authDomain: 'gotogether-5429a.firebaseapp.com',
    storageBucket: 'gotogether-5429a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHogvbYVqGapxxn3lg7a78eRDReIp7x2U',
    appId: '1:493628718680:android:76a18f8aa313372c6c142d',
    messagingSenderId: '493628718680',
    projectId: 'gotogether-5429a',
    storageBucket: 'gotogether-5429a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKw4Cm5HOUa9ZbOZ4EmoHoZN6y3CpzYhI',
    appId: '1:493628718680:ios:2164c257ef8a88766c142d',
    messagingSenderId: '493628718680',
    projectId: 'gotogether-5429a',
    storageBucket: 'gotogether-5429a.firebasestorage.app',
    iosBundleId: 'com.gotogether.mobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key',
    appId: '1:1234567890:ios:1234567890abcdef',
    messagingSenderId: '1234567890',
    projectId: 'demo-gotogether',
    storageBucket: 'demo-gotogether.appspot.com',
    iosBundleId: 'com.gotogether.mobileFlutter',
  );
}